export const experienceData = [
  {
    id: "techstudents",
    year: "August 2025 - Present (11 months)",
    degree: "Product Developer",
    field: "",
    university: "Tech Students, Nizamabad, India",
    description:
      "Designed and built an end-to-end EdTech platform using a microservices architecture, covering UI/UX, full-stack development, testing, Docker-based containerization, and deployment. Implemented 6 role-based dashboards with 13+ production-ready features, including authentication, analytics, assessments, and admin controls.",
    courses: [
      "React.js",
      "Node.js",
      "Express.js",
      "MySQL",
      "Docker",
      "Tailwind CSS",
      "TanStack Query",
      "JWT Auth",
      "Microservices",
    ],
    category: "Freelance",
    remote: false,
    link: "https://tech-students-beta.vercel.app",
  },
  {
    id: "freelance",
    year: "March 2026 - May 2026 (3 months)",
    degree: "Freelance Full Stack Developer",
    field: "",
    university: "No-company. (Self-employed.), Hyderabad, India",
    description:
      "Delivered 10+ paid final-year projects for BCA, MCA, and engineering students, covering full-stack web application development from requirement gathering to deployment. Built placement portals, student management systems, attendance systems, learning platforms, dashboards, admin panels, and business workflow applications. Worked mainly with React, Node.js, Tailwind CSS, Express, MySQL, Redux, Socket.IO, and PayPal. Prepared detailed project documentation and implementation files for each project, including 90-page DOCX reports where required.",
    courses: [
      "React",
      "Node.js",
      "Tailwind CSS",
      "Express",
      "MySQL",
      "Redux",
      "Socket.IO",
      "PayPal",
    ],
    category: "Freelance",
    remote: true,
    projectsList: [
      { name: "Market Scope", demo: "https://market-scope-ten.vercel.app", github: "https://github.com/NaveedAfraz/MarketScope" },
      { name: "Edit Flow Pro", demo: "https://edit-flow-pro.vercel.app", github: "https://github.com/NaveedAfraz/EditFlowPro" },
      { name: "Secure Net", demo: "https://secure-net-tau.vercel.app", github: "https://github.com/NaveedAfraz/SecureNet" },
      { name: "Smart Study", demo: "https://smart-study-eta-seven.vercel.app", github: "https://github.com/NaveedAfraz/SmartStudy" },
      { name: "Income Tracker", demo: "https://income-tracker-gray.vercel.app", github: "https://github.com/NaveedAfraz/IncomeTracker" },
      { name: "Pass Guard", demo: "https://pass-guard-brown.vercel.app", github: "https://github.com/NaveedAfraz/PassGuard" },
      { name: "Secure Vault", demo: "https://secure-vault-blond.vercel.app", github: "https://github.com/NaveedAfraz/SecureVault" },
      { name: "BookDrop", demo: "https://bookdrop-delta.vercel.app", github: "https://github.com/NaveedAfraz/bookdrop" },
      { name: "TournaForge", demo: "https://tourna-forge.vercel.app", github: "https://github.com/NaveedAfraz/TournaForge" },
      { name: "Tutor Near", demo: "https://tutor-near.vercel.app", github: "https://github.com/NaveedAfraz/TutorNear" },
      { name: "Estate Value", demo: "https://estate-value.vercel.app", github: "https://github.com/NaveedAfraz/EstateValue" },
      { name: "Cert Chain", demo: "https://cert-chain-gilt.vercel.app", github: "https://github.com/NaveedAfraz/cert-chain" },
      { name: "Placement Pro", demo: "https://placement-pro-alpha.vercel.app", github: "https://github.com/NaveedAfraz/Placement-pro" }
    ],
  },
  {
    id: "mshygiene",
    year: "January 2026 - April 2026 (4 months)",
    degree: "Full Stack Developer",
    field: "",
    university: "MS Hygiene Industries (IT Division), Mumbai, India",
    description:
      "Selected as a Trainee/Intern – Full-Stack E-commerce Website & Mobile App Development, contributing to multiple production-ready, end-to-end platforms across e-commerce, marketplace, social networking, and healthcare domains. Developed responsive, scalable e-commerce websites with secure payment gateway integration, built marketplace and social networking platforms aligned with real-world workflows, designed/implemented RESTful APIs, developed mobile applications integrated with backend services, and owned the entire project lifecycle from requirement analysis to deployment and optimization.",
    courses: [
      "PERN Stack",
      "React.js",
      "PostgreSQL",
      "Express.js",
      "Node.js",
      "React Native",
      "REST APIs",
      "AWS",
      "Docker",
      "Cloud Deployment",
      "Git",
      "Payment Gateway",
    ],
    category: "Internships",
    remote: true,
    projectsList: [
      { name: "MSE Org", demo: "https://mseorg.com", demoLabel: "Live Site" },
      { name: "Auramiingo", demo: "https://auramiingo.com", demoLabel: "Live Site" },
      { name: "CareKov", demo: "https://carekov.com", demoLabel: "Live Site" }
    ]
  },
  {
    id: "alprophysio",
    year: "October 2025 - January 2026 (4 months)",
    degree: "Full Stack Web Developer",
    field: "",
    university: "Alpro Physio Clinic, India",
    description:
      "Developed a modern, responsive physiotherapy website with booking and service management features. Integrated Resend for automated email notifications and inquiries. Focused on SEO optimization, accessibility, and mobile-first design.",
    courses: [
      "React.js",
      "Node.js",
      "Express.js",
      "MySQL",
      "Tailwind CSS",
      "DaisyUI",
      "Resend",
      "Render",
      "Vercel",
    ],
    category: "Freelance",
    remote: true,
    link: "https://alprophysioclinic.com",
  },
  {
    id: "infipost",
    year: "May 2025 - November 2025 (7 months)",
    degree: "Full Stack Developer Intern",
    field: "",
    university: "Infiposts Private Limited, Bengaluru, India",
    description:
      "Worked across a microservices-based architecture using Django and FastAPI on the backend and React + TypeScript on the frontend. Built the Utility Space module, contributed to API development, and developed the Task AI frontend, which was later integrated into the main system.",
    courses: [
      "React.js",
      "TypeScript",
      "Django",
      "FastAPI",
      "MySQL",
      "Tailwind CSS",
      "Docker",
      "Microservices Architecture",
    ],
    category: "Internships",
    remote: true,
  },
  {
    id: "quwwahealth",
    year: "June 2025 - July 2025 (2 months)",
    degree: "Web Developer",
    field: "",
    university: "Quwwa Health, India",
    description:
      "Responsible for the end-to-end development of a healthcare platform, implementing a responsive UI with React and designing a secure, high-performance back-end to manage all data and business logic.",
    courses: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Tailwind CSS",
      "Resend",
      "Vercel",
      "Render",
    ],
    category: "Freelance",
    remote: true,
    link: "https://quwwahealth.com",
  },
];
