export const experienceData = [
  {
    id: "infipost",
    year: "May 2025 – Present",
    degree: "Full Stack Developer Intern",
    field: "",
    university: "Infiposts Private Limited, Bengaluru, India",
    description:
      "Contributing to scalable full-stack web applications built on a microservices architecture. Developing and integrating RESTful APIs using Django and FastAPI for backend services. Collaborating with cross-functional teams to enhance performance, maintainability, and deployment efficiency.",
    courses: [
      "React.js",
      "Django",
      "FastAPI",
      "MySQL",
      "Tailwind CSS",
      "Docker",
      "Microservices Architecture",
    ],
    category: "Internships",
    remote: true,
  },
  {
    id: "techstudents",
    year: "Aug 2025 – Present",
    degree: "Full Stack Web Developer",
    field: "",
    university: "Tech Students, Hyderabad, India",
    description:
      "Built a large-scale, role-based platform offering LMS, hackathons, internships, and analytics. Implemented multi-role dashboards (students, mentors, employers) with secure OTP-based authentication. Architected and deployed backend services using Express.js within a Dockerized microservices setup.",
    courses: [
      "React.js",
      "Node.js",
      "Express.js",
      "MySQL",
      "Docker",
      "Tailwind CSS",
      "TanStack Query",
      "JWT Auth",
      "Microservices",
    ],
    category: "Freelance",
    remote: true,
    link: "https://tech-students-beta.vercel.app",
  },
  {
    id: "quwwahealth",
    year: "Jun 2025 – Jul 2025",
    degree: "Full Stack Web Developer",
    field: "",
    university: "Quwwa Health, India",
    description:
      "Built a healthcare platform for showcasing services, consultations, and patient engagement. Used Resend for appointment confirmation and contact form email automation. Ensured fast performance and elegant UI across all devices.",
    courses: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Resend",
      "Vercel",
      "Render",
    ],
    category: "Freelance",
    remote: true,
    link: "https://quwwahealth.com",
  },

  {
    id: "alprophysio",
    year: "Sep 2025 – Oct 2025",
    degree: "Full Stack Web Developer",
    field: "",
    university: "Alpro Physio Clinic, India",
    description:
      "Developed a modern, responsive physiotherapy website with booking and service management features. Integrated Resend for automated email notifications and inquiries. Focused on SEO optimization, accessibility, and mobile-first design.",
    courses: [
      "React.js",
      "Node.js",
      "Express.js",
      "MySQL",
      "Tailwind CSS",
      "DaisyUI",
      "Resend",
      "Render",
      "Vercel",
    ],
    category: "Freelance",
    remote: true,
    link: "https://alprophysioclinic.com",
  },
];
