// Project data with vibrant color transitions
export const projectsData = [
  {
    id: "bitebox",
    category: "Personal & Mini",
    title: "BiteBox",
    description:
      "Online food ordering platform with menu browsing and checkout",
    detailedDescription:
      "BiteBox is a food ordering app where customers can browse menus, customize orders, and checkout securely via Stripe. Restaurant owners get real-time order tracking with Socket.io, plus inventory and sales dashboards. Built with React, Node.js, Express, and MySQL.",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Stripe",
      "Clerk",
      "Socket.io",
      "react-redux",
      "recharts",
      "NodeJS",
    ],
    gradientFrom: "#1E3A70", // Deep blue
    gradientTo: "#2C5282", // Brighter blue
    logo: "bitebox",
    image: "/images/BIteBox.png",
    link: "https://bite-box-three.vercel.app",
  },
  {
    id: "notes",
    category: "Personal & Mini",
    title: "Notes",
    description:
      "Minimalist note-taking application with rich text editing",
    detailedDescription:
      "A clean note-taking application with rich text formatting, tags, search, and autosave. Built with React, Tailwind CSS, and a Node.js/Express backend.",
    technologies: [
      "ReactJS",
      "Tailwind CSS",
      "Moosge",
      "Shadcn",
      "Express",
      "NodeJS",
      "LocalStorage",
      "Rich Text Editor",
    ],
    gradientFrom: "#4A5568", // Slate
    gradientTo: "#1A202C", // Dark slate
    logo: "notes",
    image: "/images/Notes.png",
    link: "https://notes-dt72.onrender.com",
  },
  {
    id: "elite-wardrobe",
    category: "Personal & Mini",
    title: "Elite Wardrobe",
    description: "Clothing and accessories store with product filtering and checkout",
    detailedDescription:
      "Elite Wardrobe is an e-commerce store featuring product filtering, size guides, wishlists, and Stripe checkout. Includes an admin panel for tracking orders and stock. Built with React, Node.js, Express, and MySQL.",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Stripe",
      "React-Redux",
      "NodeJS",
      "Product Filtering",
      "Wishlist",
    ],
    gradientFrom: "#553C9A", // Purple
    gradientTo: "#805AD5", // Light purple
    logo: "elite-wardrobe",
    image: "/images/EliteWardorbe.png",
    link: "https://e-commerce-psi-inky-93.vercel.app/auth/login",
  },
  {
    id: "athena-ai",
    category: "Personal & Mini",
    title: "Athena AI",
    description:
      "AI chat assistant with voice, text, and translation capabilities",
    detailedDescription:
      "Athena AI is a conversational assistant built to answer questions, generate content, and translate languages via text or voice. Includes custom prompt tools and data export. Built with React for the frontend and Node.js/Express on the backend.",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Clerk",
      "React-Redux",
      "NodeJS",
      "AI Integration",
      "Natural Language Processing",
    ],
    gradientFrom: "#2B6CB0", // Blue
    gradientTo: "#4299E1", // Light blue
    logo: "athena-ai",
    image: "/images/AthenaBot.png",
    link: "https://athena-ai-five.vercel.app",
  },
  {
    id: "blog",
    category: "Personal & Mini",
    title: "DevInsights Blog",
    description:
      "A technical blog platform for developers to share knowledge and insights",
    detailedDescription:
      "DevInsights is a comprehensive blogging platform designed specifically for developers and tech enthusiasts. The platform allows users to create, publish, and share technical articles with rich code formatting, syntax highlighting, and embedded media. Features include categorization by topics, interactive comments section, and social sharing capabilities. The platform also includes a recommendation system that suggests relevant articles based on reading history. The clean, responsive design ensures optimal readability across all devices, while the markdown support makes technical writing effortless. Built with React.js for the frontend and a Node.js/Express backend with MySQL database.",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Clerk",
      "Markdown",
      "React-Redux",
      "Code Highlighting",
      "NodeJS",
    ],
    gradientFrom: "#C05621", // Orange
    gradientTo: "#ED8936", // Light orange
    logo: "blog",
    image: "/images/blog.png",
    link: "https://blog-theta-three-48.vercel.app/home",
  },
  {
    id: "echomate",
    category: "Personal & Mini",
    title: "EchoMate",
    description:
      "A real-time messaging platform with voice and video capabilities",
    detailedDescription:
      "EchoMate is a real-time messaging application with instant chat, read receipts, file sharing, and emoji reactions. Supports group channels, direct messages, and audio/video calls. Built with React, Socket.io, Node.js, Express, and MySQL.",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Clerk",
      "Socket.io",
      "WebRTC",
      "React-Redux",
      "NodeJS",
    ],
    gradientFrom: "#285E61", // Teal
    gradientTo: "#38B2AC", // Light teal
    logo: "echomate",
    image: "/images/EchoMate.png",
    link: "https://echomate-chat.vercel.app",
  },
  {
    id: "social-media",
    category: "Personal & Mini",
    title: "Social Media Platform",
    description:
      "A social media platform with user authentication, posting, and commenting features",
    detailedDescription:
      "A social media platform with user authentication, posting, and commenting features",
    technologies: [
      "ReactJS",
      "Shadcn",
      "Tailwind",
      "MySQL",
      "Express",
      "Clerk",
      "React-Redux",
      "Markdown",
      "Code Highlighting",
      "NodeJS",
    ],
    gradientFrom: "#285E61", // Teal
    gradientTo: "#38B2AC",
    logo: "social-media",
    image: "/images/X.png",
    link: "https://social-media-1-2enj.onrender.com/home",
  },
  {
    id: "klipp",
    category: "Client Projects",
    title: "Klipp – AI-Powered After Effects Plugin & Web Platform",
    description: "Built a commercial Adobe After Effects CEP plugin with a companion web platform for licensing, payments, and user management.",
    detailedDescription: "Built a commercial Adobe After Effects CEP plugin with a companion web platform for licensing, payments, and user management. Developed AI-powered caption generation using Whisper.cpp, multilingual translation with IndicTrans2, secure native licensing with HWID binding, encrypted model delivery, and an admin dashboard for managing licenses, pricing, releases, and users. Integrated Razorpay and Whop for payments, Better Auth for authentication, and designed a secure licensing engine communicating with the React panel via IPC.",
    technologies: ["React", "TypeScript", "Vite", "Tailwind CSS", "Node.js", "Express", "Better Auth", "MySQL", "Drizzle ORM", "Whisper.cpp", "IndicTrans2", "Cloudflare R2", "Razorpay", "Whop", "Adobe CEP", "ExtendScript"],
    gradientFrom: "#0F172A",
    gradientTo: "#0284C7",
    logo: "klipp",
    image: "/images/klipp.png",
    link: "https://fx.klipp.in",
  },
  {
    id: "techstudents",
    category: "Client Projects",
    title: "Tech Students",
    description: "EdTech platform with 6 role-based dashboards, quizzes and assessments, student analytics, and admin management.",
    detailedDescription: "Tech Students is an educational platform built with React, Node.js, and MySQL. It includes 6 role-based dashboards and 13+ features including user authentication, real-time analytics, assessment modules, and admin controls, containerized using Docker.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Docker", "JWT Auth", "TanStack Query", "Tailwind CSS"],
    gradientFrom: "#1E293B",
    gradientTo: "#475569",
    logo: "techstudents",
    image: "/images/techstudents.png",
    link: "https://techstudents.in",
  },
  {
    id: "mseorg",
    category: "Client Projects",
    title: "MSE Org",
    description: "E-commerce platform built for MS Hygiene with product catalogs, search, shopping cart, and Stripe payment checkout.",
    detailedDescription: "E-commerce platform developed for MS Hygiene Industries. Features include product catalogs, filtering and search, shopping cart, and Stripe payment checkout. The backend handles inventory management and customer order processing.",
    technologies: ["React", "Node.js", "Express", "PostgreSQL", "Stripe", "Docker", "AWS", "Tailwind CSS"],
    gradientFrom: "#1E3A8A",
    gradientTo: "#3B82F6",
    logo: "mseorg",
    image: "/images/mseorg.png",
    link: "https://mseorg.com",
  },
  {
    id: "auramiingo",
    category: "Client Projects",
    title: "Auramiingo",
    description: "Social networking and marketplace platform with real-time chat, post sharing, product reviews, and online purchases.",
    detailedDescription: "Combines social networking with an online store. Users can chat in real time, share posts, leave reviews, and purchase products. Built with React, Node.js, and PostgreSQL.",
    technologies: ["React", "Node.js", "Express", "PostgreSQL", "Socket.IO", "React Native", "Tailwind CSS"],
    gradientFrom: "#5F370E",
    gradientTo: "#854D0E",
    logo: "auramiingo",
    image: "/images/auramiingo.png",
    link: "https://auramiingo.com",
  },
  {
    id: "alprophysio",
    category: "Client Projects",
    title: "Alpro Physio Clinic",
    description: "Clinic management website with automated appointment scheduling, service listings, and email notifications via Resend.",
    detailedDescription: "Developed for Alpro Physio Clinic, this platform features patient service listings, automated online scheduling, inquiry channels, and integrated notifications via Resend. Built with React, Node.js, and MySQL.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Tailwind CSS", "Resend", "Render"],
    gradientFrom: "#065F46",
    gradientTo: "#0F766E",
    logo: "alprophysio",
    image: "/images/alprophysio.png",
    link: "https://alprophysioclinic.com",
  },
  {
    id: "quwwahealth",
    category: "Client Projects",
    title: "Quwwa Health",
    description: "Healthcare website with appointment booking, health inquiry forms, and patient consultation dashboards.",
    detailedDescription: "Quwwa Health is a web application for healthcare consultations, featuring patient inquiry tracking, consulting dashboards, and automated email notifications.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "Resend", "Vercel"],
    gradientFrom: "#451A03",
    gradientTo: "#78350F",
    logo: "quwwahealth",
    image: "/images/quwwahealth.png",
    link: "https://quwwahealth.com",
  },
  {
    id: "carekov",
    category: "Client Projects",
    title: "CareKov",
    description: "Clinic management portal for patient records, online appointment scheduling, and doctor-patient messaging.",
    detailedDescription: "CareKov is a digital healthcare portal for managing patient records, scheduling appointments, writing digital prescriptions, and doctor-patient communication.",
    technologies: ["React", "Node.js", "Express", "PostgreSQL", "React Native", "Tailwind CSS"],
    gradientFrom: "#1C3D5A",
    gradientTo: "#006677",
    logo: "carekov",
    image: "/images/carekov.png",
    link: "https://carekov.com",
  },
  {
    id: "marketscope",
    category: "Academic Freelance (Paid)",
    title: "Market Scope",
    description:
      "An advanced market analytics and scanning platform for business insights",
    detailedDescription:
      "Market Scope is a data-driven intelligence tool designed to scan, track, and analyze business metrics. Built with React and Express, it provides visually rich charts, customizable filters, and detailed reports that help organizations scope market trends and evaluate opportunities.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Chart.js", "Tailwind CSS"],
    gradientFrom: "#2C3E50",
    gradientTo: "#3498DB",
    logo: "marketscope",
    link: "https://market-scope-ten.vercel.app",
  },
  {
    id: "editflowpro",
    category: "Academic Freelance (Paid)",
    title: "Edit Flow Pro",
    description:
      "A collaborative team workflow management system for content editors",
    detailedDescription:
      "Edit Flow Pro streamlines content and editorial pipelines. It features article submission trackers, assignment boards, editorial feedback comments, and role-based permissions to organize workflow between writers and editors.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Redux", "Tailwind CSS"],
    gradientFrom: "#111827",
    gradientTo: "#3B82F6",
    logo: "editflowpro",
    link: "https://edit-flow-pro.vercel.app",
  },
  {
    id: "securenet",
    category: "Academic Freelance (Paid)",
    title: "Secure Net",
    description:
      "A network monitoring portal showcasing logs and security metrics",
    detailedDescription:
      "Secure Net is a visual web dashboard designed to simulate and display network activities and security analysis. It tracks firewall log files, highlights active alerts, and uses real-time WebSockets to notify administrators of security incidents.",
    technologies: ["React", "Node.js", "Express", "Socket.IO", "Tailwind CSS", "MySQL"],
    gradientFrom: "#065F46",
    gradientTo: "#059669",
    logo: "securenet",
    link: "https://secure-net-tau.vercel.app",
  },
  {
    id: "smartstudy",
    category: "Academic Freelance (Paid)",
    title: "Smart Study",
    description:
      "An interactive student portal for assessments, tracking, and resources",
    detailedDescription:
      "Smart Study offers students and educators an easy-to-use platform for sharing syllabus files, taking mock examinations, scoring assessments, and logging study progress. Designed to improve academic productivity and organization.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Tailwind CSS", "Redux"],
    gradientFrom: "#1E3A8A",
    gradientTo: "#3B82F6",
    logo: "smartstudy",
    link: "https://smart-study-eta-seven.vercel.app",
  },
  {
    id: "incometracker",
    category: "Academic Freelance (Paid)",
    title: "Income Tracker",
    description:
      "A personal finance tracker for organizing expenses, budgets, and savings",
    detailedDescription:
      "Income Tracker allows individuals to log daily transactions, structure monthly budgets, tag expenses, and visualize income streams over time. Includes exportable reports and visual analytics for financial wellness.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "Chart.js"],
    gradientFrom: "#064E3B",
    gradientTo: "#10B981",
    logo: "incometracker",
    link: "https://income-tracker-gray.vercel.app",
  },
  {
    id: "passguard",
    category: "Academic Freelance (Paid)",
    title: "Pass Guard",
    description:
      "A secure local credentials safe with password generation utilities",
    detailedDescription:
      "Pass Guard is a secure local credentials manager. It features strong password generation, localized database encryption, and metadata sorting parameters to safely store and organize sensitive login accounts.",
    technologies: ["React", "Node.js", "Express", "Cryptography", "Tailwind CSS", "LocalStorage"],
    gradientFrom: "#701A75",
    gradientTo: "#D946EF",
    logo: "passguard",
    link: "https://pass-guard-brown.vercel.app",
  },
  {
    id: "securevault",
    category: "Academic Freelance (Paid)",
    title: "Secure Vault",
    description:
      "An encrypted web cabinet for file storage and secure sharing workflows",
    detailedDescription:
      "Secure Vault provides an encrypted platform to upload, store, and manage files. Integrates cryptographic sharing links and access timers to ensure files are only accessible to authorized collaborators.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Cryptography", "Tailwind CSS"],
    gradientFrom: "#311042",
    gradientTo: "#701A75",
    logo: "securevault",
    link: "https://secure-vault-blond.vercel.app",
  },
  {
    id: "bookdrop",
    category: "Academic Freelance (Paid)",
    title: "BookDrop",
    description:
      "A lightweight book reservation and library inventory platform",
    detailedDescription:
      "BookDrop simplifies cataloging and borrowing books. Designed for schools or small libraries, it handles reserve queues, checkout timers, user histories, and admin inventory listings with ease.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
    gradientFrom: "#7C2D12",
    gradientTo: "#F97316",
    logo: "bookdrop",
    link: "https://bookdrop-delta.vercel.app",
  },
  {
    id: "tournaforge",
    category: "Academic Freelance (Paid)",
    title: "TournaForge",
    description:
      "A tournament structure designer and live matches bracket generator",
    detailedDescription:
      "TournaForge automates tournament management. It dynamically generates single-elimination brackets, logs match outcomes, updates standings in real-time, and integrates chat rooms for competitors.",
    technologies: ["React", "Node.js", "Express", "Socket.IO", "Tailwind CSS", "MySQL"],
    gradientFrom: "#1E1B4B",
    gradientTo: "#4F46E5",
    logo: "tournaforge",
    link: "https://tourna-forge.vercel.app",
  },
  {
    id: "tutornear",
    category: "Academic Freelance (Paid)",
    title: "Tutor Near",
    description:
      "A local tutor marketplace for matches, scheduling, and learning tasks",
    detailedDescription:
      "Tutor Near connects students with local academic guides. It incorporates interactive maps, scheduling calendars, billing options, and rating systems to simplify finding and scheduling tuition sessions.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Google Maps API", "Tailwind CSS"],
    gradientFrom: "#451A03",
    gradientTo: "#D97706",
    logo: "tutornear",
    link: "https://tutor-near.vercel.app",
  },
  {
    id: "estatevalue",
    category: "Academic Freelance (Paid)",
    title: "Estate Value",
    description:
      "A real estate pricing estimator and property listings platform",
    detailedDescription:
      "Estate Value provides a comprehensive interface for browsing property listings, analyzing real estate statistics, and using mathematical estimation models to evaluate property valuation estimates.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Tailwind CSS"],
    gradientFrom: "#065F46",
    gradientTo: "#047857",
    logo: "estatevalue",
    link: "https://estate-value.vercel.app",
  },
  {
    id: "certchain",
    category: "Academic Freelance (Paid)",
    title: "Cert Chain",
    description:
      "A cryptographically verified credentials and PDF certificate generator",
    detailedDescription:
      "Cert Chain enables institutions to issue tamper-proof certificates. It features cryptographic signatures, unique verification keys, automated PDF generation, and public verification links.",
    technologies: ["React", "Node.js", "Express", "Cryptography", "PDFKit", "Tailwind CSS"],
    gradientFrom: "#311042",
    gradientTo: "#6366F1",
    logo: "certchain",
    link: "https://cert-chain-gilt.vercel.app",
  },
  {
    id: "placementpro",
    category: "Academic Freelance (Paid)",
    title: "Placement Pro",
    description:
      "A university placement dashboard for job posts and resume submissions",
    detailedDescription:
      "Placement Pro is a unified recruitment portal for students and college admins. It helps organize job vacancy notices, manage student resumes, track application steps, and generate statistics.",
    technologies: ["React", "Node.js", "Express", "MySQL", "Tailwind CSS", "Redux"],
    gradientFrom: "#1E3A8A",
    gradientTo: "#1D4ED8",
    logo: "placementpro",
    link: "https://placement-pro-alpha.vercel.app",
  },
];
